package com.touchetime.wizard.utils.colors

import androidx.compose.ui.graphics.Color

open class WizardThemeColors protected constructor(
    val backgroundBrand: Color,
    val backgroundBrandLight: Color,
    val backgroundPrimary: Color,
    val backgroundSecondary: Color,
    val backgroundTertiary: Color,
    val backgroundInverse: Color,
    val backgroundAlwaysDark: Color,
    val backgroundAlwaysLight: Color,
    val contentBrand: Color,
    val contentBrandLight: Color,
    val contentPrimary: Color,
    val contentSecondary: Color,
    val contentTertiary: Color,
    val contentDisabled: Color,
    val contentInverse: Color,
    val contentAlwaysDark: Color,
    val contentAlwaysLight: Color,
    val strokeBrand: Color,
    val strokeBrandLight: Color,
    val strokePrimary: Color,
    val strokeSecondary: Color,
    val strokeTertiary: Color,
    val strokeInverse: Color,
) {
    companion object {
        @JvmStatic
        fun create(
            backgroundBrand: Color,
            backgroundBrandLight: Color,
            backgroundPrimary: Color,
            backgroundSecondary: Color,
            backgroundTertiary: Color,
            backgroundInverse: Color,
            backgroundAlwaysDark: Color,
            backgroundAlwaysLight: Color,
            contentBrand: Color,
            contentBrandLight: Color,
            contentPrimary: Color,
            contentSecondary: Color,
            contentTertiary: Color,
            contentDisabled: Color,
            contentInverse: Color,
            contentAlwaysDark: Color,
            contentAlwaysLight: Color,
            strokeBrand: Color,
            strokeBrandLight: Color,
            strokePrimary: Color,
            strokeSecondary: Color,
            strokeTertiary: Color,
            strokeInverse: Color,
        ): WizardThemeColors =
            WizardThemeColors(
                backgroundBrand = backgroundBrand,
                backgroundBrandLight = backgroundBrandLight,
                backgroundPrimary = backgroundPrimary,
                backgroundSecondary = backgroundSecondary,
                backgroundTertiary = backgroundTertiary,
                backgroundInverse = backgroundInverse,
                backgroundAlwaysDark = backgroundAlwaysDark,
                backgroundAlwaysLight = backgroundAlwaysLight,
                contentBrand = contentBrand,
                contentBrandLight = contentBrandLight,
                contentPrimary = contentPrimary,
                contentSecondary = contentSecondary,
                contentTertiary = contentTertiary,
                contentDisabled = contentDisabled,
                contentInverse = contentInverse,
                contentAlwaysDark = contentAlwaysDark,
                contentAlwaysLight = contentAlwaysLight,
                strokeBrand = strokeBrand,
                strokeBrandLight = strokeBrandLight,
                strokePrimary = strokePrimary,
                strokeSecondary = strokeSecondary,
                strokeTertiary = strokeTertiary,
                strokeInverse = strokeInverse,
            )
    }
}
